services:
  db:
    image: postgres:16-alpine
    container_name: insider-db
    environment:
      POSTGRES_DB: insider
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      # $ değişkenlerini compose’un genişletmemesi için $$ kullandık
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 2s
      timeout: 2s
      retries: 15
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: insider-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  migrator:
    image: migrate/migrate:4
    container_name: insider-migrator
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./internal/db/migrations:/migrations:ro
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/insider?sslmode=disable
    entrypoint: ["/bin/sh", "-lc"]
    command: >
      'migrate -path /migrations -database "$$DATABASE_URL" up || true; tail -f /dev/null'
    restart: on-failure

  app:
    build: .
    container_name: insider-app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      migrator:
        condition: service_started
    environment:
      APP_ENV: dev
      HTTP_PORT: 8080
      # DİKKAT: container içinden DB host ismi 'db' olmalı (localhost değil)
      DATABASE_URL: postgres://postgres:postgres@db:5432/insider?sslmode=disable
      JWT_SECRET: supersecret
      JWT_ISSUER: insider-backend
    ports:
      - "8080:8080"
    command: ["/app/api"]
    restart: on-failure

volumes:
  pgdata: {}
